# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21eac319c5290dfe94670f7847d6c207edf924202490d45c192cca3573368cd9b6fd60447f9c7494f8c62d2ec8c7a6106f1bf6557bd8915a7757e5d606452673

test:
  secret_key_base: a2bc07846d7086af5995c09b83bcaf44cd485ef19c89f1c56b368ff888acd0e98a97bc60a6d0f1b80a0abb94fdce8378974eb21a963877a4fdaf9769be0c3a53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
